/**
 * Load the content written for the canvas designs into Payload.
 *
 *   npm run seed
 *
 * Wipes and recreates departments, specialists, offices and media (unless SEED_ONLY_IF_EMPTY=true and content exists).
 * content.json is generated by design/export_content.py; images live in ./media.
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { getPayload } from 'payload'
import config from '@payload-config'

const dirname = path.dirname(fileURLToPath(import.meta.url))
const content = JSON.parse(fs.readFileSync(path.join(dirname, 'content.json'), 'utf8'))
const mediaDir = path.join(dirname, 'media')

type TD = [string, string]
const pairs = (items?: TD[]) => (items || []).map(([title, description]) => ({ title, description }))
const texts = (items?: string[]) => (items || []).map((text) => ({ text }))

const payload = await getPayload({ config })

// On Vercel the build runs this with SEED_ONLY_IF_EMPTY=true, so a fresh database gets the content once and editors' changes are never wiped.
if (process.env.SEED_ONLY_IF_EMPTY === 'true') {
  const { totalDocs } = await payload.count({ collection: 'departments' })
  if (totalDocs > 0) {
    payload.logger.info(`Database already has ${totalDocs} departments; skipping seed`)
    process.exit(0)
  }
}

for (const collection of ['departments', 'specialists', 'offices', 'media'] as const) {
  await payload.delete({ collection, where: { id: { exists: true } } })
}

// Media: one upload per image id used in the content, with alt text from where it's used.
const alts = new Map<string, string>()
for (const d of content.departments) {
  if (d.logo) alts.set(d.logo, `${d.brand} logo`)
  if (d.photo) alts.set(d.photo, d.photoAlt)
  if (d.home?.photo) alts.set(d.home.photo, d.home.photoAlt)
  if (d.feature?.image) alts.set(d.feature.image, d.feature.img_alt || d.feature.heading)
}
for (const s of content.specialists) if (s.photo) alts.set(s.photo, s.name)
for (const o of content.offices) if (o.photo) alts.set(o.photo, o.photoAlt)

const files = fs.readdirSync(mediaDir)
const mediaIds = new Map<string, number>()
for (const [blob, alt] of alts) {
  const file = files.find((f) => f.startsWith(blob))
  if (!file) {
    payload.logger.warn(`missing image ${blob} (${alt})`)
    continue
  }
  const doc = await payload.create({ collection: 'media', data: { alt }, filePath: path.join(mediaDir, file) })
  mediaIds.set(blob, doc.id)
}
const media = (blob?: string | null) => (blob ? mediaIds.get(blob) : undefined)

const officeIds = new Map<string, number>()
for (const [order, o] of content.offices.entries()) {
  const doc = await payload.create({ collection: 'offices', data: { ...o, photoAlt: undefined, photo: media(o.photo), order } })
  officeIds.set(o.slug, doc.id)
}
const offices = (keys: string[]) => keys.map((k) => officeIds.get(k)).filter((x): x is number => x !== undefined)

const specialistIds = new Map<string, number>()
for (const s of content.specialists) {
  const doc = await payload.create({
    collection: 'specialists',
    data: {
      name: s.name,
      slug: s.slug,
      role: s.role,
      title: s.title || undefined,
      photo: media(s.photo),
      offices: offices(s.offices),
      bio: texts(s.bio),
      sections: s.sections,
    },
  })
  specialistIds.set(s.slug, doc.id)
}

for (const d of content.departments) {
  const t = d.treatments
  const f = d.feature
  await payload.create({
    collection: 'departments',
    data: {
      name: d.name,
      slug: d.slug,
      order: d.order,
      tag: d.tag,
      brand: d.brand,
      shortBrand: d.shortBrand,
      logo: media(d.logo),
      phone: d.phone,
      phoneLabel: d.phoneLabel,
      bookLabel: d.bookLabel,
      eyebrow: d.eyebrow,
      headline: d.headline,
      intro: d.intro,
      photo: media(d.photo)!,
      photoPosition: d.photoPosition,
      heroSecondaryLabel: d.heroSecondary?.[0],
      heroSecondaryHref: d.heroSecondary?.[1],
      facts: d.facts,
      home: { ...d.home, photo: media(d.home.photo) },
      overview: {
        eyebrow: d.overview.eyebrow,
        heading: d.overview.heading,
        paras: texts(d.overview.paras),
        glanceTitle: d.overview.glance_title,
        glance: d.overview.glance,
        note: d.overview.note,
      },
      reviews: d.reviews,
      conditions: {
        navLabel: d.conditions.navLabel,
        eyebrow: d.conditions.eyebrow,
        heading: d.conditions.heading,
        lede: d.conditions.lede,
        items: pairs(d.conditions.items),
        programs: (d.conditions.programs || []).map((p: Record<string, unknown>) => ({
          title: p.title,
          summary: p.summary,
          conditions: p.conditions,
          procedures: p.procedures,
          procLabel: p.proc_label || 'Treatments and procedures',
          more: p.more,
        })),
      },
      treatments: t
        ? { enabled: true, navLabel: t.navLabel, eyebrow: t.eyebrow, heading: t.heading, lede: t.lede, items: pairs(t.items) }
        : { enabled: false },
      feature: f
        ? {
            enabled: true,
            onPatientsPage: f.onPatientsPage,
            navLabel: f.navLabel,
            eyebrow: f.eyebrow,
            heading: f.heading,
            paras: texts(f.paras),
            chips: f.chips,
            bullets: texts(f.bullets),
            links: f.links,
            image: media(f.image),
          }
        : { enabled: false },
      visit: { eyebrow: d.visit.eyebrow, heading: d.visit.heading, steps: pairs(d.visit.steps), note: d.visit.note, linkLabel: d.visit.link },
      resources: d.resources,
      faq: d.faq,
      faqOpen: d.faqOpen,
      team: {
        eyebrow: d.team.eyebrow,
        heading: d.team.heading,
        emptyNote: d.team.empty,
        members: d.team.members.map((slug: string) => specialistIds.get(slug)).filter((x: number | undefined): x is number => x !== undefined),
      },
      offices: offices(d.offices),
      officePhone: d.officePhone,
      whereHeading: d.whereHeading,
      whereNote: d.whereNote,
      ctaHeading: d.ctaHeading,
    },
  })
}

payload.logger.info(
  `Seeded ${content.departments.length} departments, ${specialistIds.size} specialists, ${officeIds.size} offices, ${mediaIds.size} images`,
)
process.exit(0)
