/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    departments: Department;
    specialists: Specialist;
    offices: Office;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    departments: DepartmentsSelect<false> | DepartmentsSelect<true>;
    specialists: SpecialistsSelect<false> | SpecialistsSelect<true>;
    offices: OfficesSelect<false> | OfficesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments".
 */
export interface Department {
  id: number;
  /**
   * e.g. Allergy, asthma & immunology
   */
  name: string;
  /**
   * Page address: /care/<slug>
   */
  slug: string;
  order?: number | null;
  /**
   * Short label for office cards and filters, e.g. ENT
   */
  tag: string;
  /**
   * e.g. SH Allergy, Asthma & Immunology
   */
  brand: string;
  /**
   * Shown in the department header, e.g. SH Allergy
   */
  shortBrand: string;
  /**
   * White logo on transparent background. Without one, a placeholder badge is shown.
   */
  logo?: (number | null) | Media;
  phone: string;
  /**
   * e.g. Allergy
   */
  phoneLabel: string;
  /**
   * e.g. Book an allergy appointment
   */
  bookLabel: string;
  eyebrow: string;
  /**
   * Use *asterisks* for italic and **double asterisks** for bold.
   */
  headline: string;
  intro: string;
  photo: number | Media;
  /**
   * CSS object-position, e.g. center 30%
   */
  photoPosition?: string | null;
  /**
   * Second hero button; defaults to calling the department
   */
  heroSecondaryLabel?: string | null;
  heroSecondaryHref?: string | null;
  facts?:
    | {
        big: string;
        small: string;
        id?: string | null;
      }[]
    | null;
  home: {
    /**
     * Used in “Explore …” on the home page
     */
    short: string;
    summary: string;
    chips?: string[] | null;
    photo?: (number | null) | Media;
    photoPosition?: string | null;
  };
  overview: {
    eyebrow?: string | null;
    heading: string;
    paras?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    glanceTitle?: string | null;
    glance?: string[] | null;
    note?: string | null;
  };
  reviews?:
    | {
        quote: string;
        attribution?: string | null;
        id?: string | null;
      }[]
    | null;
  conditions: {
    /**
     * Name of this page in the department menu; the page address is made from it.
     */
    navLabel?: string | null;
    eyebrow?: string | null;
    heading: string;
    lede?: string | null;
    items?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional sub-specialty panels (used by ENT and Surgery) instead of simple cards
     */
    programs?:
      | {
          title: string;
          summary: string;
          conditions?: string[] | null;
          procedures?: string[] | null;
          procLabel?: string | null;
          more?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  treatments?: {
    enabled?: boolean | null;
    /**
     * Name of this page in the department menu; the page address is made from it.
     */
    navLabel?: string | null;
    eyebrow?: string | null;
    heading?: string | null;
    lede?: string | null;
    items?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * A page of its own, such as Shot clinic or Hearing aids
   */
  feature?: {
    enabled?: boolean | null;
    /**
     * Show on the Patients page instead of as its own page
     */
    onPatientsPage?: boolean | null;
    /**
     * Name of this page in the department menu; the page address is made from it.
     */
    navLabel?: string | null;
    eyebrow?: string | null;
    heading?: string | null;
    paras?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    chips?: string[] | null;
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    links?: string[] | null;
    image?: (number | null) | Media;
  };
  visit: {
    eyebrow?: string | null;
    heading: string;
    steps?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    note?: string | null;
    linkLabel?: string | null;
  };
  resources?:
    | {
        /**
         * Material Symbols icon name, e.g. description
         */
        icon?: string | null;
        title: string;
        description?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        /**
         * Start lines with “- ” for a bulleted list.
         */
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * How many answers start open
   */
  faqOpen?: number | null;
  team?: {
    eyebrow?: string | null;
    heading?: string | null;
    members?: (number | Specialist)[] | null;
    emptyNote?: string | null;
  };
  offices?: (number | Office)[] | null;
  /**
   * Phone shown for every office on the department pages
   */
  officePhone?: string | null;
  whereHeading: string;
  whereNote?: string | null;
  ctaHeading: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialists".
 */
export interface Specialist {
  id: number;
  /**
   * With credentials, e.g. Jacob Johnson, MD
   */
  name: string;
  slug: string;
  /**
   * One short line shown on cards
   */
  role: string;
  /**
   * Full professional title for the profile page
   */
  title?: string | null;
  photo?: (number | null) | Media;
  offices?: (number | Office)[] | null;
  bio?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Education, memberships, hospital affiliations and similar lists
   */
  sections?:
    | {
        heading: string;
        items?: string[] | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offices".
 */
export interface Office {
  id: number;
  name: string;
  slug: string;
  region: 'San Francisco' | 'Peninsula' | 'South Bay' | 'East Bay' | 'North Bay';
  street: string;
  /**
   * City, state and ZIP, e.g. San Francisco, CA 94108
   */
  city: string;
  phone?: string | null;
  hours?: string | null;
  /**
   * One short line, e.g. Our home since 1945
   */
  note?: string | null;
  photo?: (number | null) | Media;
  /**
   * Latitude, for the map and “nearest office”
   */
  lat?: number | null;
  /**
   * Longitude
   */
  lng?: number | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'departments';
        value: number | Department;
      } | null)
    | ({
        relationTo: 'specialists';
        value: number | Specialist;
      } | null)
    | ({
        relationTo: 'offices';
        value: number | Office;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments_select".
 */
export interface DepartmentsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  order?: T;
  tag?: T;
  brand?: T;
  shortBrand?: T;
  logo?: T;
  phone?: T;
  phoneLabel?: T;
  bookLabel?: T;
  eyebrow?: T;
  headline?: T;
  intro?: T;
  photo?: T;
  photoPosition?: T;
  heroSecondaryLabel?: T;
  heroSecondaryHref?: T;
  facts?:
    | T
    | {
        big?: T;
        small?: T;
        id?: T;
      };
  home?:
    | T
    | {
        short?: T;
        summary?: T;
        chips?: T;
        photo?: T;
        photoPosition?: T;
      };
  overview?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        paras?:
          | T
          | {
              text?: T;
              id?: T;
            };
        glanceTitle?: T;
        glance?: T;
        note?: T;
      };
  reviews?:
    | T
    | {
        quote?: T;
        attribution?: T;
        id?: T;
      };
  conditions?:
    | T
    | {
        navLabel?: T;
        eyebrow?: T;
        heading?: T;
        lede?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        programs?:
          | T
          | {
              title?: T;
              summary?: T;
              conditions?: T;
              procedures?: T;
              procLabel?: T;
              more?: T;
              id?: T;
            };
      };
  treatments?:
    | T
    | {
        enabled?: T;
        navLabel?: T;
        eyebrow?: T;
        heading?: T;
        lede?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  feature?:
    | T
    | {
        enabled?: T;
        onPatientsPage?: T;
        navLabel?: T;
        eyebrow?: T;
        heading?: T;
        paras?:
          | T
          | {
              text?: T;
              id?: T;
            };
        chips?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        links?: T;
        image?: T;
      };
  visit?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        steps?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        note?: T;
        linkLabel?: T;
      };
  resources?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        href?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  faqOpen?: T;
  team?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        members?: T;
        emptyNote?: T;
      };
  offices?: T;
  officePhone?: T;
  whereHeading?: T;
  whereNote?: T;
  ctaHeading?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialists_select".
 */
export interface SpecialistsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  title?: T;
  photo?: T;
  offices?: T;
  bio?:
    | T
    | {
        text?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        heading?: T;
        items?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offices_select".
 */
export interface OfficesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  region?: T;
  street?: T;
  city?: T;
  phone?: T;
  hours?: T;
  note?: T;
  photo?: T;
  lat?: T;
  lng?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}